#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("HanoiAir.Resource", IsApplication=true)]

namespace HanoiAir
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int crying = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int gasmask = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int sad = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int smiling = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int adviceText = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int aqiLabel = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int aqiValue = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int forecast = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int gauge = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int getAlerts = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int refreshStatus = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int textView1 = 2131099655;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Icon = 2130903041;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f05000c
			public const int badAdvice = 2131034124;
			
			// aapt resource value: 0x7f050008
			public const int badQuality = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int currentAirQuality = 2131034115;
			
			// aapt resource value: 0x7f05000e
			public const int descriptionFormat = 2131034126;
			
			// aapt resource value: 0x7f050012
			public const int forecastDown = 2131034130;
			
			// aapt resource value: 0x7f05000f
			public const int forecastFormat = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int forecastSame = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int forecastSameOrDown = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int forecastSameOrUp = 2131034131;
			
			// aapt resource value: 0x7f050010
			public const int forecastUp = 2131034128;
			
			// aapt resource value: 0x7f050002
			public const int getAirQualityAlerts = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int goodAdvice = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int goodQuality = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int iconMadeByFreepikFromWwwFlaticonComLicensedUnderCCBY30 = 2131034116;
			
			// aapt resource value: 0x7f05000b
			public const int poorAdvice = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int poorQuality = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int refreshStatus = 2131034117;
			
			// aapt resource value: 0x7f05000d
			public const int terribleAdvice = 2131034125;
			
			// aapt resource value: 0x7f050009
			public const int terribleQuality = 2131034121;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
